### ISSUE TITLE
choose course controller の挙動を一部 Ajax にする

### ISSUE THREAD

**Issue by hzcyto** [PICC-WATC/E-Stud#3]
@dododoSA がやってたセレクトボックスの改良を行ってみた。  
ブランチ：choose_course_fix にそれを試みたので確認よろしく。  
私はいまだに bcrypt が上手く挙動しないためにテストできないので。

**Comment by dododoSA** [comment]
![image](https://user-images.githubusercontent.com/32331100/54358532-fa08b900-46a3-11e9-8222-7f91a5b5a505.png)
このハッシュで囲まれたやつとかで解決しないかな？

**Comment by dododoSA** [comment]
![image](https://user-images.githubusercontent.com/32331100/54358720-62f03100-46a4-11e9-8bae-f10fb6ffdaf5.png)

**Comment by dododoSA** [comment]
![image](https://user-images.githubusercontent.com/32331100/54359589-51a82400-46a6-11e9-9448-f05c85ed9954.png)
l_dataのパラメータがnilになってるわ

**Comment by hzcyto** [comment]
bcryptのに関して、
元々bcrypt-rubyは抜いてたし、消したり、インストールしなおしたりと
色々な組み合わせやったけどダメだった。

**Comment by hzcyto** [comment]
別の動かせる環境を作った。
そしてそれでこないだ作ったやつ動かしたら私が創造してたのと違う…となり
大幅な修正を実施、ちゃんと動くようになったよー

**Comment by PICC-WATC** [comment]
このタスクのプルリクを確認。
マージしても問題なさげだったのでmasterにマージしておいた。
一応 @dododoSA も挙動の確認(masterで)お願い。

**Comment by hzcyto** [comment]
完了したので close します。
